### ISSUE TITLE
IE9 Unable to post XMLHttpRequest when formData contains a File

### ISSUE THREAD

**Issue by fayway** [moxiecode/moxie#125]
Context:
````
<html>
<head>
    <script type="text/javascript" src="lib/moxie/bin/js/moxie.js"></script>
    <script>mOxie.Env.swf_url = 'lib/moxie/bin/flash/Moxie.swf';</script>
</head>
<body>
    <div id="container">
        <input id="file-picker" type="file" >
    </div>
    <script>
        var fileInput = new mOxie.FileInput({
            browse_button: 'file-picker'
        });

        fileInput.onchange = function(e) {
            var file = e.target.files[0];
            console.log ( file instanceof mOxie.File ) ;

            var formData = new mOxie.FormData();
            formData.append('key', 'value');
            formData.append('file', file );

            var xhr = new mOxie.XMLHttpRequest();
            xhr.open('POST', '/sandbox/uploadhandler.php', true);
            xhr.send(formData);
        };

        fileInput.init();
    </script>
</body>
</html>
````

Problem: No post request is sent using IE9, but when commenting the line that append the file to formData
````
//formData.append('file', file );
````
The post request is sent
![capture1](https://cloud.githubusercontent.com/assets/1507839/7270133/061452c6-e8da-11e4-977e-ec312f78ed5e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1507839/7270135/0a73c34c-e8da-11e4-98ba-9c7ba71149d2.PNG)

The same first code (formData with File) is ok with Chrome:
![capture3](https://cloud.githubusercontent.com/assets/1507839/7270148/28ea17f4-e8da-11e4-9a46-4cff7f721914.PNG)

Is there a workaround to be able to send the **formData with a File via XmlHttpRequest Post** ?

Regards

**Comment by tstirrat** [comment]
I'm getting the same problem. It appears to be a problem in the `flash` runtime only, silverlight works fine. Sadly silverlight is not an option for my use case.

I tried the flash runtime in chrome, same problem.

I checked out `bin/flash/Moxie.min.swf` all the way back to version 1.0.0 and the problem still persists.

**Comment by tstirrat** [comment]
btw here is the code I am using: 

```js
mOxie.Env.swf_url = 'bower_components/moxie/bin/flash/Moxie.min.swf';
mOxie.Env.xap_url = 'bower_components/moxie/bin/silverlight/Moxie.min.xap';

var fileInput = new mOxie.FileInput({
  runtime_order: 'flash,html5',
  browse_button: 'file-field',
});
fileInput.init();

document.getElementById('go').addEventListener('click', function (e) {
  e.preventDefault();

  if (fileInput.files && fileInput.files.length) {
    var formData = new mOxie.FormData();
    formData.append('key', 'value');
    formData.append('file', fileInput.files[0]);

    var xhr = new mOxie.XMLHttpRequest();
    xhr.open('POST', '/api/upload', true);
    xhr.send(formData);
  }
});
```

If I send the file directly as the body of the post with `xhr.send(fileInput.files[0]);` it works, but this does not send as multi-part (which is required for my needs)

**Comment by jayarjo** [comment]
Strangely enough I can't repeat this on IE8. File just uploads. Will get VM for IE9.

**Comment by jayarjo** [comment]
Tried in IE9, Windows 7, FP 10.3.183.67. Uploads with your code. Have you tried binaries from the latest release (v1.2.2) maybe?

**Comment by irbian** [comment]
Ey, I think I have found a regression/culprit on this one

I have something like this

    var formData = new moxie.xhr.FormData();
    formData.append('file', file)
    var xhr = new moxie.xhr.XMLHttpRequest();
    xhr.open('POST', '/api/upload', true);
    xhr.send(formData);
   
The browser is IE9 emulated and the initialized runtime is flash. Now, I have found what it seems is a problem here and is that:
a) this line never enter https://github.com/moxiecode/moxie/blob/master/src/javascript/runtime/flash/xhr/XMLHttpRequest.js#L69, the blob is not one of the fields
b) this https://github.com/moxiecode/moxie/blob/master/src/javascript/runtime/flash/xhr/XMLHttpRequest.js#L75 dont work, but "if (!data._blob) {" work
c) this https://github.com/moxiecode/moxie/blob/master/src/javascript/runtime/flash/xhr/XMLHttpRequest.js#L79 doesnt work, but "var blob = data._blob.value;" work

This problem could be related with https://github.com/moxiecode/moxie/issues/38 ? Because while debugging I have gotten GET requests (I think that when the blob where setted to null)

Let me know what you think

**Comment by kostia7alania** [comment]
7777
